// 作品集项目数据：与简历对齐
// type: 'image' 有截图用图片卡片；'text' 用文字卡片
export const projects = [
  {
    id: 1,
    name: "Super Easy AI Web",
    type: "text",
    link: "",
    desc: "Nuxt4 AI 创作平台，主导前端架构。设计动态 AI App 渲染引擎，按配置自动渲染 10+ 类型控件；轮询重构为 WebSocket + Pinia 任务状态机，实现刷新恢复、终态锁定与任务取消。",
    tags: ["Nuxt4", "TypeScript", "WebSocket", "Stripe"],
  },
  {
    id: 2,
    name: "Easeware ECC 后台",
    type: "text",
    link: "",
    desc: "内部运营后台，负责整体工程搭建与权限体系（动态菜单/路由守卫/按钮指令），封装 Axios 请求层（Token 刷新、401 重试）；抽象通用 DataTable 支持万级数据筛选导出，构建体积 19MB→7MB。",
    tags: ["Vue3", "Element Plus", "Webpack", "权限体系"],
  },
  {
    id: 3,
    name: "supereasy.com 插件体系",
    type: "text",
    link: "https://www.supereasy.com/",
    desc: "开发维护约 30 个 WordPress 插件、10+ 转化类 Gutenberg Block（基于 React 实现编辑器组件），将内容增长需求产品化；建设 People Search 与工具页体系，支持校验、reCAPTCHA 与 tracking。",
    tags: ["WordPress", "PHP", "React", "Gutenberg"],
  },
  {
    id: 4,
    name: "Easeware Zendesk App",
    type: "text",
    link: "",
    desc: "从 0 到 1 开发工单侧边栏应用，自动解析邮箱与 License Key，实现双维度订单聚合查询；封装订单查询/退款/退订/自动扣款接口，降低误操作与二次工单风险。",
    tags: ["Zendesk SDK", "Vue3", "订单系统"],
  },
  {
    id: 5,
    name: "Driver Easy 多语种站点",
    type: "text",
    link: "https://www.drivereasy.com/",
    desc: "维护英/德/法/意/西/日购买页与购买组件，支持 7-day free trial 与 URL 参数联动；重构 Contact Us 为模板+后台配置，开发 unsubscribe 接入 reCAPTCHA，改造异步表单。",
    tags: ["多语种", "国际化", "reCAPTCHA"],
  },
  {
    id: 6,
    name: "IM SDK",
    type: "image",
    link: "https://open.lwim.cn/doc/",
    image: "@/assets/images/about/im-sdk.webp",
    desc: "负责 IM SDK 技术选型与架构设计，选定 Rollup 打包；封装二进制封包/拆包、WebSocket、文件上传模块，Canvas 图片压缩。",
    tags: ["JS SDK", "WebSocket", "Rollup"],
  },
  {
    id: 7,
    name: "可访 APP Flutter 版",
    type: "image",
    link: "https://www.kefangapp.com/#/download",
    image: "@/assets/images/about/kefang-flutter.webp",
    desc: "基于 Flutter 开发的 IM 聊天软件（可访），独立完成跨平台实现。",
    tags: ["Flutter", "IM"],
  },
  {
    id: 8,
    name: "可访 Web 版",
    type: "image",
    link: "https://web.kefangapp.com/",
    image: "@/assets/images/about/kefang.webp",
    desc: "Vue 全家桶构建可访网页版，扫码登录、地图消息、Vant + rem 移动端适配。",
    tags: ["Vue", "Vant", "移动端"],
  },
  {
    id: 9,
    name: "领兀云官网",
    type: "image",
    link: "https://www.lwim.cn/",
    image: "@/assets/images/about/lingwuyun.webp",
    desc: "云服务官网，负责全部前端开发与维护。",
    tags: ["官网", "响应式"],
  },
  {
    id: 10,
    name: "开发者平台",
    type: "image",
    link: "https://open.lwim.cn/",
    image: "@/assets/images/about/kaifazhe.webp",
    desc: "开发者平台，权限/工单/直播管理模块开发。",
    tags: ["Vue", "后台管理"],
  },
  {
    id: 11,
    name: "爱华盈通官网",
    type: "image",
    link: "https://www.aiwinn.com/",
    image: "@/assets/images/about/aihuayigtong.webp",
    desc: "企业官网及宣传类 H5 开发与维护。",
    tags: ["官网", "H5"],
  },
];

// 作品页精选（最新项目优先）
export const featuredProjects = projects.slice(0, 6);
